# Copyright 2023 Aineko Authors
# SPDX-License-Identifier: Apache-2.0
site_name: Aineko
site_url: https://docs.aineko.dev/
repo_name: aineko-dev/aineko
repo_url: https://github.com/aineko-dev/aineko
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - mkdocs-click

plugins:
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            extension:
              - griffe_typingdoc
            show_root_heading: true

nav:
  - Home: 'index.md'
  - Quickstart: 'quickstart.md'
  - Developer Guide:
      - Deeper Dive: 'developer_guide/deeper_dive.md'
      - Concepts: 'developer_guide/concepts.md'
      - CLI Guide: 'developer_guide/cli_guide.md'
      - Pipeline Configuration: 'developer_guide/pipeline_configuration.md'
      - Node Implementation: 'developer_guide/node_implementation.md'
  - Troubleshooting: 'troubleshooting.md'
  - Examples:
      - Aineko Dream: examples/aineko-dream.md
  - Contributing: 'contributing.md'
  - Aineko Cloud: 'aineko_cloud.md'
