# Copyright 2023 Aineko Authors
# SPDX-License-Identifier: Apache-2.0
site_name: Aineko
site_url: https://docs.aineko.dev/
repo_name: aineko-dev/aineko
repo_url: https://github.com/aineko-dev/aineko
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            extension:
              - griffe_typingdoc
            show_root_heading: true

nav:
  - Home: 'index.md'
  - Quickstart: 'quickstart.md'
  - Developer Guide:
      - 'developer_guide/deeper_dive.md'
      - 'developer_guide/concepts.md'
      - 'developer_guide/cli_guide.md'
      - 'developer_guide/pipeline_configuration.md'
      - 'developer_guide/node_implementation.md'
  - API Reference:
      - 'api_reference/abstract_node.md'
      - 'api_reference/dataset.md'
      - 'api_reference/config_loader.md'
      - 'api_reference/runner.md'
  - Troubleshooting: 'troubleshooting.md'
  - Examples:
      - examples/aineko-dream.md
  - Contributing: 'contributing.md'
  - Aineko Cloud: 'aineko_cloud.md'
